# Generated by Django 2.0.7 on 2018-08-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20180812_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_repo',
            field=models.URLField(blank=True, max_length=80, null=True),
        ),
    ]
