# Generated by Django 2.0.7 on 2019-04-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20180812_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas_group',
            name='category_text',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
