# Generated by Django 2.0.7 on 2019-06-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_idea_idea_proposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='idea_proposal',
            new_name='content',
        ),
    ]
