name: test_ideas_actions
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python ./manage.py test
        env:
          SYSTEM_ENV: GITHUB_WORKFLOW
